### ISSUE TITLE
certificate (Itemwise,RegNowise,Schoolwise) not coming for spo participant

### ISSUE THREAD

**Issue by rashivkp** [itschool/kalolsavam-subdistrict#8]
checked db for entries in result_master, certificate_master and participant_item_details. all rows are present there.

case: Reg.No4584 DRISHYA P M (11053 - C. H. S. S. Chattanchal(Kasaragod)) appeal entry got first place in Kathaprasangam(HSS general)

**Comment by rashivkp** [comment]
for this participant result_master contains rank but no rank present in certificate master

**Comment by rashivkp** [comment]
cause of issue: the certificate_master contain grade of participant who comes from the same school, its not the actual captain's grade.

**Comment by rthcupid** [comment]
result_master contain admn_no column as double, changed it to varchar(10).
then result has been reset, and confirmed it. now the certificate produced correctly.
