### ISSUE TITLE
total number of paricipant is incorrect in list of certificate

### ISSUE THREAD

**Issue by rthcupid** [itschool/kalolsavam-subdistrict#9]
kalolsavam_subdistrict_2013/index.php/certificate/certificate/list_item_wise

![screenshot from 2013-12-06 11 38 58](https://f.cloud.github.com/assets/3539220/1690159/f6d0cb24-5e3c-11e3-9200-697ee512ec63.png)

**Comment by rashivkp** [comment]
fixed in 52e088aea672d5fdd10432a76ff92fbd50eb8529
